### ISSUE TITLE
Invoke operation: specify datatype of the parameters

### ISSUE THREAD

**Issue by RobinHerbots** [progress/CDO#4]
@sbschase, @PeterJudge-Psc, @edselg, @mikefechner

According the specification it should be possible to specify the datatype of the parameters in invoke (custom) operations.

> xType Specifies parameter data type. Can be one of the following: “TABLE” “DATASET” “ARRAY” (for array of objects) json datatype: either “string”, “integer”, “number”, “boolean” ABL datatype: see OE ABL datatype mapping chart If “TABLE”, “DATASET”, or “ARRAY” is specified, then its schema needs to be specified in the resource’s dataDefinitions property.

But we don't manage to make this appear in the catalog.  Can somebody help out?

This is an example from the documentation

{
"name": "GetFamilyCount",
"path": "/GetFamilyCount",
"useBeforeImage": false,
"type": "invoke",
"verb": "put",
"params": [{
          "name": "numMembers",
          **"xType": "INTEGER",**
"type": "RESPONSE_BODY"
}

**Comment by edselg** [comment]
Hello @RobinHerbots 

The catalog generation in PDSOE supports the dataDefinitions property so that you can include  TEMP-TABLEs and DATASETs.

However, my understanding is that the usage of xType to include information on scalar data types was not implemented in the catalog generation.

Is this an issue that you are finding as you continue implementing NCDO?
Thank you for your interest on the CDO and your work on NCDO.
Link:
* https://github.com/RobinHerbots/NCDO

Is this something that is limiting you in your development?
Could you elaborate on this?
I believe there was a similar question not long ago on this subject.
We could bring it to Product Management for prioritization.

Thank you and regards.

**Comment by RobinHerbots** [comment]
Hi @edselg , 
Yes.
NCDO is mainly used in combination of a clientgenerator (NCDO_Clientgen).  
The clientgeneration is based on the catalog.  Due to the missing type declaration for custom operation it is not possible to generate the correct type in the dotnet client.
The only thing I can do now is resolving the type to string or guessing by the name used of the parameter.  
It would be really helpfull.  Even if you could provide a patch we can apply for testing.

Best regards, 
Robin
